name: build-exe

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyinstaller

      - name: Build EXE
        run: |
          python -m PyInstaller --clean --onefile --windowed app.py --name keyword_tool

     - name: Upload EXE Artifact
  uses: actions/upload-artifact@v4
  with:
    name: keyword_tool
    path: dist/keyword_tool.exe
